version: "3"

services:
  excessiveplus:
    image: myq3srv
    restart: always
    ports:
      - "27960:27960/udp"
    volumes:
      - "${PWD}/excessiveplus:/usr/lib/ioquake3/excessiveplus"
      - "${PWD}/baseq3:/usr/lib/ioquake3/baseq3"
      - "${PWD}/launcher.sh:/usr/lib/ioquake3/launcher.sh"
      - "${PWD}/.q3a:/home/q3user_svc/.q3a"

